# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20161222_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='height_field', null=True, upload_to=post.models.upload_location, width_field='width_field'),
        ),
    ]
